version: '3.8'
services:

  app:
    container_name: app_mail
   #image: app &&  python sender.py >> log_sender.txt &
    build: .
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8001 --reload "
    ports:
      - "8001:8001"
    env_file:
      - .env
    restart: always
  db:
    container_name: mail_db
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=MailSender